spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/Shobanal1990/config-server-repo
          uri: https://github.com/LnAgrawal/ecommerce-config-repo
          clone-on-start: true
          default-label: main

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    ip-address: true
server:
  port: 8686