spring:
  reactor:
    context-propagation: auto
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost/ecommerce
    username: sa
    password: sa@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    ip-address: true
server:
  port: 8282

logging:
  file:
    name: orderservice.log
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: B3
    enabled: true